### ISSUE TITLE
Relevancy

### ISSUE THREAD

**Issue by DavidEdwards** [toomasr/skype-bot#8]
Is this code still relevant?

I have a feeling that Microsoft has changed a lot.

For example, the first step requiring me to create a project at http://developer.skype.com is not possible. That I can see.

**Comment by toomasr** [comment]
Not relevant anymore. Microsoft stopped the Skype API. More info at https://aragonresearch.com/microsoft-kills-skype-desktop-apis-leaves-developers-scrambling/
